---
kind: pipeline
type: docker
name: Install phpLDAPadmin

clone:
  depth: 1

steps:

  - name: docker build & push
    image: plugins/docker
    settings:
      mirror: dockerhub.nexus.diesel.net
      registry: docker.nexus.diesel.net
      username:
        from_secret: nexus_user
      password:
        from_secret: nexus_pass
      repo: docker.nexus.diesel.net/${DRONE_REPO_NAME}
      tags:
        - ${DRONE_BRANCH}-latest
    when:
      branch:
        - development
        - stable
      event:
        - push


  - name: configure & deploy (development)
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
    settings:
      inventory: .ansible/inventory/development/hosts
      playbook: .ansible/deploy.yaml
      galaxy: .ansible/roles/requirements.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password
    when:
      branch:
        - development
      event:
        - push

  - name: configure & deploy (production)
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      LDAP_ADMIN_PASSWORD:
        from_secret: ldap_admin_password
    settings:
      playbook: .ansible/deploy.yaml
      inventory: .ansible/inventory/production/hosts
      galaxy: .ansible/roles/requirements.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password
    when:
      branch:
        - stable
      event:
        - push

trigger:
  branch:
    - development
    - stable
  event:
    - push
...
