---
kind: pipeline
type: docker
name: Deploy phpLDAPadmin (dev)

clone:
  depth: 1

concurrency:
  limit: 1

steps:

  - name: docker build & push
    image: plugins/docker
    settings:
      mirror: dockerhub.nexus.diesel.net
      registry: docker.nexus.diesel.net
      username:
        from_secret: nexus_user
      password:
        from_secret: nexus_pass
      repo: docker.nexus.diesel.net/${DRONE_REPO_NAME}
      tags:
        - ${DRONE_BRANCH}-latest



  - name: configure & deploy
    image: docker.nexus.diesel.net/drone-ansible:2.13
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
    settings:
      inventory: .ansible/inventory/dev
      playbook: .ansible/deploy.yaml
      galaxy: .ansible/roles/requirements.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password

trigger:
  branch:
    - development
  event:
    - push

---
kind: pipeline
type: docker
name: Deploy phpLDAPadmin (prod)

clone:
  depth: 1

concurrency:
  limit: 1

steps:

  - name: docker build & push
    image: plugins/docker
    settings:
      mirror: dockerhub.nexus.diesel.net
      registry: docker.nexus.diesel.net
      username:
        from_secret: nexus_user
      password:
        from_secret: nexus_pass
      repo: docker.nexus.diesel.net/${DRONE_REPO_NAME}
      tags:
        - production-latest
        - ${DRONE_TAGE}


  - name: configure & deploy
    image: docker.nexus.diesel.net/drone-ansible:2.13
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
    settings:
      inventory: .ansible/inventory/prod
      playbook: .ansible/deploy.yaml
      galaxy: .ansible/roles/requirements.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password

trigger:
  branch:
    - stable
  event:
    - push

...
