# ansible-playbook deploy.yaml -i inventories/prod/hosts --vault-id ~/.tokens/master_id

- hosts: tools
  strategy: linear
  tasks:

    - include_role:
        name: docker
        tasks_from: stack_deploy


