# ansible-playbook deploy.yaml -i inventories/prod/hosts --vault-id ~/.tokens/master_id

- hosts: tools
  strategy: linear
  roles:
    - common

  tasks:

    - include_role:
        name: common
        tasks_from: make_config_dir

    - include_role:
        name: common
        tasks_from: make_data_dir

    - include_role:
        name: docker
        tasks_from: stack_deploy


